# Generated by Django 3.2.4 on 2021-06-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=250, verbose_name='Номер телефона клиента'),
        ),
    ]
