# Generated by Django 3.2.4 on 2021-06-15 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_shop', '0004_alter_product_discount'),
        ('inbox', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ecommerce_shop.product', verbose_name='Заказаный товар'),
        ),
    ]
